flask_news/models.py
from sqlalchemy import Column, String, Integer, DateTime, ForeignKey
from sqlalchemy.orm import declarative_base, relationship
from datetime import datetime


Base = declarative_base()


class NewsModel(Base):
    __tablename__ = 'news'
    id = Column(Integer, primary_key=True)
    title = Column(String, nullable=False)
    url = Column(String, nullable=False)
    created_at = Column(DateTime, default=datetime.now(), nullable=False)


class PageModel(Base):
    __tablename__ = 'pages'
    id = Column(Integer, primary_key=True)
    name = Column(String, nullable=False)
    news_site_id = Column(Integer, ForeignKey('news_sites.id'))

    def __str__(self) -> str:
        return self.name


class NewsSiteModel(Base):
    __tablename__ = 'news_sites'
    id = Column(Integer, primary_key=True)
    domain = Column(String, nullable=False)
    titles_selector = Column(String, nullable=False)
    urls_selector = Column(String, nullable=False)
    pages = relationship('PageModel')

flask_news/forms.py
from wtforms import StringField, URLField
from wtforms.validators import DataRequired
from flask_wtf import FlaskForm

from .fields import NewsSiteField


class AddNewsSiteForm(FlaskForm):
    site_domain = URLField(validators=[DataRequired()])
    titles_selector = StringField(validators=[DataRequired()])
    urls_selector = StringField(validators=[DataRequired()])


class AddPageForm(FlaskForm):
    site = NewsSiteField(validators=[DataRequired()])
    name = StringField(validators=[DataRequired()])

flask_news/__init__.py
from flask import Flask
from sqlalchemy.engine import Engine
from sqlalchemy.orm import Session

from .views import bp


class FlaskNews:

    def __init__(self, app: Flask = None, db: Engine = None) -> None:
        if app is not None and db is not None:
            self.init_app(app, db)

    def init_app(self, app: Flask, db: Engine) -> None:
        app.news_getter = self
        app.db = db
        app.db_session = Session(db)
        app.register_blueprint(bp)

flask_news/app.py
from flask import Flask
from sqlalchemy import create_engine
from dotenv import load_dotenv
import os

from flask_news import FlaskNews


def create_app(testing: bool = False) -> Flask:
    app = Flask(__name__, static_folder='static', template_folder='templates')
    load_dotenv('.env')
    app.testing = testing
    app.config['SECRET_KEY'] = os.getenv('SECRET_KEY')
    db = create_engine(os.getenv('SQLALCHEMY_DATABASE_URI'))
    FlaskNews(app, db)
    return app

flask_news/views.py
from flask import Blueprint, Response, render_template, redirect, url_for

from .forms import AddNewsSiteForm, AddPageForm


bp = Blueprint('flask_news', __name__, url_prefix='/news',
               template_folder='templates', static_folder='static')


@bp.get('/')
def index() -> Response:
    return render_template('flask_news/index.html')


@bp.get('/add-news-site')
def add_news_site_get() -> Response:
    return render_template('flask_news/add_news_site.html', form=AddNewsSiteForm())


@bp.post('/add-news-site')
def add_news_site_post() -> Response:
    return redirect(url_for('.add_news_site_get'))


@bp.get('/add-page')
def add_page_get() -> Response:
    return render_template('flask_news/add_page.html', form=AddPageForm())


@bp.post('/add-page')
def add_page_post() -> Response:
    return redirect(url_for('.add_page_get'))

flask_news/templates/flask_news/add_news_site.html
{% extends "flask_news/base.html" %}

{% block title %}Adicionar site de noticias{% endblock %}

{% block content %}
  <div class="container vh-100">
    <div class="row h-100 justify-content-center align-items-center">
      <div class="col-sm-7">
        <form class="form border-rounded" method="post" action="{{ url_for('flask_news.add_news_site_post') }}">
          {{ form.csrf_token }}
          <div class="row mb-3">
            {{ form.site_domain.label(class_="form-label") }}
            {{ form.site_domain(class_="form-control") }}
          </div>
          <div class="row mb-3">
            {{ form.titles_selector.label(class_="form-label") }}
            {{ form.titles_selector(class_="form-control") }}
          </div>
          <div class="row mb-3">
            {{ form.urls_selector.label(class_="form-label") }}
            {{ form.urls_selector(class_="form-control") }}
          </div>
          <div class="row justify-content-center">
            <button class="btn" type="submit">Adicionar</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

flask_news/templates/flask_news/add_page.html
{% extends "flask_news/base.html" %}

{% block title %}Adicionar site de noticias{% endblock %}

{% block content %}
  <div class="container vh-100">
    <div class="row h-100 justify-content-center align-items-center">
      <div class="col-sm-7">
        <form class="form border-rounded" method="post" action="{{ url_for('flask_news.add_news_site_post') }}">
          {{ form.csrf_token }}
          <div class="row mb-3">
            {{ form.site.label(class_="form-label") }}
            {{ form.site(class_="form-select") }}
          </div>
          <div class="row mb-3">
            {{ form.name.label(class_="form-label") }}
            {{ form.name(class_="form-control") }}
          </div>
          <div class="row justify-content-center">
            <button class="btn" type="submit">Adicionar</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

flask_news/templates/flask_news/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <title>{% block title %}{% endblock %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="{{ url_for('.static', filename='signs_calculator/css/main.css') }}">
  {% block head %}{% endblock %}
</head>
<body>
  {% block content %}
  {% endblock %}
  {% block scripts %}
  {% endblock %}
</body>
</html>

flask_news/templates/flask_news/index.html
{% extends 'flask_news/base.html' %}

{% block content %}
  {% for n in news %}
    <a href="{{ n.url }}">{{ n.title }}</a>
  {% endfor %}
{% endblock %}

flask_news/templates/news_getter/index.html
{% extend 'news_getter/base.html' %}

{% block content %}
  {% for n in news %}
  <a href="{{ n.url }}">{{ n.title }}</a>
  {% endfor %}
{% endblock %}